#!/usr/bin/env python3
"""Generate docs/store.md — the store ISA, from the source of truth.

Every public function in src/store.py, with its signature and the first line of its
docstring, rendered via stdlib inspect. Regenerate with:

    uv run python scripts/gen_store_doc.py

Tests re-run this and diff (tests/unit/test_store_doc.py), so the page cannot drift
from the module it documents.
"""

from __future__ import annotations

import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import store  # noqa: E402


def render() -> str:
    lines = [
        "# The store ISA",
        "",
        "Every public function in `src/store.py`, generated by `scripts/gen_store_doc.py`",
        "via stdlib `inspect` — never edited by hand; a test regenerates and diffs this page.",
        "",
    ]
    for name, fn in sorted(vars(store).items()):
        if not inspect.isfunction(fn) or fn.__module__ != "store" or name.startswith("_"):
            continue
        doc = inspect.getdoc(fn) or ""
        summary = doc.split("\n")[0] if doc else "(undocumented)"
        sig = inspect.signature(fn, eval_str=True)
        lines.append(f"- `{name}{sig}` — {summary}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    out = ROOT / "docs" / "store.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text(render(), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
