"""Run: uv run --group dev python -m pytest tests

The size policy's own blind spot (#638): sz.py measures the files CORE_FILES and
EXTRA_FILES name and nothing else, so a file *created* under src/ but never listed was
invisible to every mode — not measured, no cap demanded, --check green no matter how
large it grew. The docstring's promise that "a file added to CORE_FILES cannot slip past
the policy" was true and beside the point: the slip happens one step earlier, by not
adding the file at all. Verified live against #122's proposed src/platform_lock.py — 29
code lines of a primitive every store write would have gone through, entirely unmeasured
(#254 discussion).

The guard mirrors the missing-cap rule it sits next to: the enforcing modes (--check,
--caps) refuse to run while an unlisted src/*.py exists, naming the file; the default
report mode still prints its table, because reporting what *is* measured never depended
on the tree being fully listed. The listing itself stays manual — the fix makes omission
loud, it does not decide caps for anyone.

These tests run sz.py the way CI does — as a subprocess against a tree — but against a
scratch copy: the real sz.py dropped into tmp_path beside a six-file src/ and a baseline
regenerated by its own --update-baseline, so the fixture tracks the real measurement
logic instead of hand-maintained numbers.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CORE = ("app.py", "config.py", "didkey.py", "limit.py", "store.py")


def _run(root: Path, *flags: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(root / "sz.py"), *flags],
        capture_output=True,
        text=True,
        check=False,
    )


def _seed(root: Path) -> None:
    """A minimal fully-listed tree: every CORE/EXTRA file present, caps generous."""
    shutil.copy(REPO / "sz.py", root / "sz.py")
    src = root / "src"
    src.mkdir()
    for name in (*CORE, "manifest.py"):
        (src / name).write_text(f'NAME = "{name}"\n', encoding="utf-8")
    caps = {f"core/{name}": 99 for name in CORE}
    caps["core_total"] = 999
    (root / "sz-baseline.json").write_text(
        json.dumps({"core_total": 0, "caps": caps, "files": {}}) + "\n", encoding="utf-8"
    )
    regen = _run(root, "--update-baseline")
    assert regen.returncode == 0, regen.stderr


def test_fully_listed_tree_checks_ok(tmp_path: Path) -> None:
    _seed(tmp_path)
    check = _run(tmp_path, "--check")
    assert check.returncode == 0, check.stderr
    assert "check ok" in check.stdout


def test_unlisted_src_file_fails_enforcing_modes(tmp_path: Path) -> None:
    _seed(tmp_path)
    (tmp_path / "src" / "rogue.py").write_text("GROWTH = None\n", encoding="utf-8")

    for flag in ("--check", "--caps"):
        refused = _run(tmp_path, flag)
        assert refused.returncode == 1, f"{flag} passed with an unmeasured src file"
        assert "src/rogue.py" in refused.stderr
        assert "CORE_FILES" in refused.stderr


def test_unlisted_file_in_subdirectory_is_still_caught(tmp_path: Path) -> None:
    _seed(tmp_path)
    nested = tmp_path / "src" / "sub"
    nested.mkdir()
    (nested / "hidden.py").write_text("GROWTH = None\n", encoding="utf-8")

    refused = _run(tmp_path, "--check")
    assert refused.returncode == 1
    assert "src/sub/hidden.py" in refused.stderr


def test_report_mode_never_needed_the_listing_and_still_does_not(tmp_path: Path) -> None:
    _seed(tmp_path)
    (tmp_path / "src" / "rogue.py").write_text("GROWTH = None\n", encoding="utf-8")

    report = _run(tmp_path)
    assert report.returncode == 0, report.stderr
    assert "core total" in report.stdout
